//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachQuyen
    {
        public string IDNhom { get; set; }
        public string IDQuyen { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhomNhanVien NhomNhanVien { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
