//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public int id { get; set; }
        public string hoTen { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string noiDung { get; set; }
        public System.DateTime ngayGui { get; set; }
        public bool TinhTrang { get; set; }
    }
}
