//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTri
    {
        public string username { get; set; }
        public string password { get; set; }
        public bool tinhTrang { get; set; }
        public string maNV { get; set; }
        public string IDNhom { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhomNhanVien NhomNhanVien { get; set; }
    }
}
